fix: resolve pre-push error

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,3 +1,3 @@
 echo "🚀 Running tests 🚀"  
-npm test:unit || (echo "Failed: test erros" && exit 1)
+npm test || (echo "Failed: test erros" && exit 1)
 echo "Done"
